export enum ActionTypes {
    COUNT = 'COUNT',
    MINUS = 'MINUS',
    CHANGE_NUMBER = 'CHANGE_NUMBER',
    FETCH_PRODUCT = 'LIST_PRODUCT/FETCH_PRODUCT',
    ADD_TO_CART = 'CART/ADD_TO_CART',
    UPDATE_QUANTITY_CART = 'CART/UPDATE_QUANTITY',
    DELETE_CART_ITEM = 'CART/DELETE_ITEM',
    PURCHASE = 'CART/DELETE_ALL'
}